os:
 - linux
 - osx
 - windows

dist: focal

osx_image: xcode12.3

language: cpp

install:
 - cd ..
 - wget https://www.scintilla.org/scintilla500.zip
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 7z x scintilla500.zip ; else unzip scintilla500.zip ; fi
 - cd lexilla

compiler:
 - gcc
 - clang

script:
 - cd src
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then mingw32-make ; else make ; fi
 - cd ..
 - cd test
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then mingw32-make test ; else make test ; fi
