os:
 - linux
 - osx
 - windows

dist: focal

osx_image: xcode12.3

language: cpp

before_install:
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install hg ; fi

install:
 - cd ..
 - hg clone http://hg.code.sf.net/p/scintilla/code scintilla
 - cd lexilla

compiler:
 - gcc
 - clang

script:
 - cd src
 - make
 - cd ..
 - cd test
 - make test
