name: "Build and check Lexilla"

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:    
            matrix:
                cpp_compiler: [g++, clang++]

        steps:
        - uses: actions/checkout@v2
        - name: Install Scintilla source
          run: |
              (cd .. && wget --no-verbose https://www.scintilla.org/scintilla500.zip)
              (cd .. && unzip scintilla500.zip)
        - name: Build
          run: (cd src && make DEBUG=1 CXX=${{matrix.cpp_compiler}})
        - name: Unit Test
          run: (cd test/unit && make DEBUG=1 test)
          env:
              CXX: ${{ matrix.cpp_compiler }}
        - name: Test
          run: (cd test && make DEBUG=1 test)
          env:
              CXX: ${{ matrix.cpp_compiler }}
        - name: Examples
          run: |
              cd examples
              (cd CheckLexilla && make DEBUG=1 check)
              (cd SimpleLexer && make DEBUG=1 check)
              cd ..
          env:
              CXX: ${{ matrix.cpp_compiler }}
